version: "3.6"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: 'interview-answers'
      MYSQL_USER: 'user'
    healthcheck:
      test: ["CMD", "mysqlshow"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - 3600
    networks:
      - back-tier
  phpfpm:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - front-tier
    depends_on:
      - mysql


networks:
  front-tier:
  back-tier: