version: "3.6"
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'interview-answers'
      MYSQL_USER: 'user'
    expose:
      - 3600
    networks:
      - back-tier
    volumes:
      - ./mysql:/var/lib/mysql


networks:
  front-tier:
  back-tier: